version: '3'
services:
  api:
    container_name: meentig-api
    build:
      context: './'
      dockerfile: ./docker/api.dockerfile
    restart: always
    volumes:
      - ./:/api/
    ports:
      - 5007:5007


